const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAIL: 'USER_SIGNUP_FAIL',
    GET_DATA_USER: "GET_DATA_USER",
    CREATE_USER_API: 'CREATE_USER_API',
    GET_POSTS_BY_TIME: 'GET_POSTS_BY_TIME'





})

export default actionTypes;